 # ./docker-compose.yml
version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    volumes:
      - ./db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: notify
      MYSQL_USER: xdrs
      MYSQL_PASSWORD: xdrs
    ports:
      - "3306:3306"
  web:
    build: ./
    restart: always
    container_name: notify-app
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
      - "./apache-volume:/etc/apache2/sites-available"
    ports:
      - "80:80"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
      - web
    ports:
      - "8181:80"
    environment:
      MYSQL_USER: root
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: 'sc-redis'
    image: redis:latest
    ports:
      - "6379:6379"